#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &

~/.config/bspwm/autostart.sh

bspc monitor -d 1 2 3 4 5

bspc config border_width 0
bspc config border_radius        0
bspc config window_gap          12

# bspc config focused_border_color "#89b4fa"
# bspc config focused_border_color "#a6e3a1"
# bspc config focused_border_color "#1d1d2d"
