#!/bin/bash

FILE="$HOME/.cache/cached_theme"
KITTY="$HOME/.config/bspwm/apps/kitty/kitty.conf"
BAR="$HOME/.config/bspwm/apps/polybar/config.ini"
GTK="$HOME/.xsettingsd"
ROFI="$HOME/.config/bspwm/apps/rofi/config.rasi"
NEOVIM="$HOME/.config/nvim/lua/user/colorscheme.lua"
EWW="$HOME/.config/bspwm/apps/eww/eww.scss"
DUNST="$HOME/.config/bspwm/autostart.sh"
JGMENU="$HOME/.config/bspwm/apps/jgmenu/run"

if [[ ! -f "$FILE" ]]; then
  touch "$FILE"
fi

if grep -q "Dark" "$FILE"; then
  # DO LIGHT THEME HERE
  sed -i '/include/c\include ~\/.config\/bspwm\/apps\/kitty\/colors\/latte.conf' $KITTY
  sed -i '/include-file=~\/.config\/bspwm\/apps\/polybar\/colors/c\include-file=~\/.config\/bspwm\/apps\/polybar\/colors\/latte.ini' $BAR
  sed -i '/Net\/ThemeName/c\Net\/ThemeName "Catppuccin-Latte-Standard-Blue-Light"' $GTK
  sed -i '/@import "colors/c\@import "colors\/latte.rasi"' $ROFI
  sed -i '/flavour = "/c\flavour = "latte"' $NEOVIM
  sed -i "/@import 'colors\//c\@import 'colors\/latte';" $EWW
  sed -i "/dunst -config/c\dunst -config ~\/.config\/bspwm\/apps\/dunst\/latte-dunstrc &" $DUNST
  sed -i "/conf_file=/c\conf_file=\$base/latte-jgmenurc" $JGMENU
  killall jgmenu
  killall dunst
  killall xsettingsd
  xdotool key ctrl+shift+F5
  bspc wm -r
  notify-send "Switched to Catppuccin Latte!"
  echo "Light" > $FILE
else
  sed -i '/include/c\include ~\/.config\/bspwm\/apps\/kitty\/colors\/mocha.conf' $KITTY
  sed -i '/include-file=~\/.config\/bspwm\/apps\/polybar\/colors/c\include-file=~\/.config\/bspwm\/apps\/polybar\/colors\/mocha.ini' $BAR
  sed -i '/Net\/ThemeName/c\Net\/ThemeName "Catppuccin-Mocha-Standard-Blue-Dark"' $GTK
  sed -i '/@import "colors/c\@import "colors\/mocha.rasi"' $ROFI
  sed -i '/flavour = "/c\flavour = "mocha"' $NEOVIM
  sed -i "/@import 'colors\//c\@import 'colors\/mocha';" $EWW
  sed -i "/dunst -config/c\dunst -config ~\/.config\/bspwm\/apps\/dunst\/mocha-dunstrc &" $DUNST
  sed -i "/conf_file=/c\conf_file=\$base/mocha-jgmenurc" $JGMENU
  killall jgmenu
  killall dunst
  killall xsettingsd
  xdotool key ctrl+shift+F5
  bspc wm -r
  notify-send "Switched to Catppuccin Mocha!"
  echo "Dark" > $FILE
fi
